name: Local CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Build Docker image locally
      - name: Build Docker image
        run: docker build -t my-flask-app .

      # Step 4: Run container and test
      - name: Run container
        run: |
          docker run -d --name test-container -p 5000:5000 my-flask-app
          sleep 5
          curl http://localhost:5000
          docker stop test-container
          docker rm test-container

